/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SuperShop;

import java.io.*;
import java.sql.*;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        setTitle("SuperShop Management System");
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    void loadTable(DefaultTableModel model) {
        String sql = "SELECT id, name, quantity, price FROM products"; // Query to fetch data

        try {
            dbConnect db = new dbConnect();
            db.connect();
            Connection conn = db.getConnection();

            PreparedStatement pstmt = conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            model.setRowCount(0); // Clear existing data

            while (rs.next()) {
                int id = rs.getInt("id");
                String name = rs.getString("name");
                int stock = rs.getInt("quantity");
                double price = rs.getDouble("price");

                // Add row to the table
                model.addRow(new Object[]{id, name, stock, price});
            }

            rs.close();
            pstmt.close();
            conn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Database Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void saveReportAsCSV(String filePath) {
        String customerName = JOptionPane.showInputDialog(null, "Enter Customer Name:");
        if (customerName == null || customerName.trim().isEmpty()) {
            return;
        }

        String phoneNo = JOptionPane.showInputDialog(null, "Enter Customer Phone No:");
        if (phoneNo == null || phoneNo.trim().isEmpty()) {
            return;
        }

        try (BufferedWriter writer = new BufferedWriter(new FileWriter(filePath))) {
            DefaultTableModel reportModel = (DefaultTableModel) reportTable.getModel();

            // Write customer info
            writer.write("Customer Name," + customerName.trim());
            writer.newLine();
            writer.write("Customer Phone," + phoneNo.trim());
            writer.newLine();
            writer.newLine(); // extra line before the table

            // Write column headers
            for (int col = 0; col < reportModel.getColumnCount(); col++) {
                writer.write(reportModel.getColumnName(col));
                if (col < reportModel.getColumnCount() - 1) {
                    writer.write(",");
                }
            }
            writer.newLine();

            // Write rows
            for (int row = 0; row < reportModel.getRowCount(); row++) {
                for (int col = 0; col < reportModel.getColumnCount(); col++) {
                    writer.write(reportModel.getValueAt(row, col).toString());
                    if (col < reportModel.getColumnCount() - 1) {
                        writer.write(",");
                    }
                }
                writer.newLine();
            }

            JOptionPane.showMessageDialog(null, "Report saved successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Error saving report!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jScrollBar1 = new javax.swing.JScrollBar();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        sellSearch = new javax.swing.JTextField();
        searchItem = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        sellTable = new javax.swing.JTable();
        addData = new javax.swing.JButton();
        loadData = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        basketTable = new javax.swing.JTable();
        confirmSale = new javax.swing.JButton();
        editQuantity = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        stockSearch = new javax.swing.JTextField();
        searchItemStock = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        stockTable = new javax.swing.JTable();
        addItemStock = new javax.swing.JButton();
        removeItemStock = new javax.swing.JButton();
        loadDataStock = new javax.swing.JButton();
        stockProductName = new javax.swing.JTextField();
        stockPrice = new javax.swing.JTextField();
        stockQuantity = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        reportTable = new javax.swing.JTable();
        genReport = new javax.swing.JButton();
        btnDownload = new javax.swing.JButton();
        performLogout = new javax.swing.JButton();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        searchItem.setText("Search Item");
        searchItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchItemActionPerformed(evt);
            }
        });

        sellTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Available Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(sellTable);
        if (sellTable.getColumnModel().getColumnCount() > 0) {
            sellTable.getColumnModel().getColumn(0).setResizable(false);
            sellTable.getColumnModel().getColumn(1).setResizable(false);
            sellTable.getColumnModel().getColumn(2).setResizable(false);
            sellTable.getColumnModel().getColumn(3).setResizable(false);
        }

        addData.setText("Add To Basket");
        addData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDataActionPerformed(evt);
            }
        });

        loadData.setText("Load Data");
        loadData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadDataActionPerformed(evt);
            }
        });

        basketTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Price", "Quantity", "Total Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(basketTable);

        confirmSale.setText("Confirm Sale");
        confirmSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmSaleActionPerformed(evt);
            }
        });

        editQuantity.setText("Edit Quantity");
        editQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editQuantityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addComponent(sellSearch))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loadData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(confirmSale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sellSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchItem))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(addData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loadData))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(confirmSale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editQuantity)))
                .addGap(19, 19, 19))
        );

        jTabbedPane1.addTab("Sell Item", jPanel1);

        searchItemStock.setText("Search");
        searchItemStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchItemStockActionPerformed(evt);
            }
        });

        stockTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Current Stock", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(stockTable);

        addItemStock.setText("Add Item");
        addItemStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemStockActionPerformed(evt);
            }
        });

        removeItemStock.setText("Remove Item");
        removeItemStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeItemStockActionPerformed(evt);
            }
        });

        loadDataStock.setText("Load Data");
        loadDataStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadDataStockActionPerformed(evt);
            }
        });

        stockQuantity.setText("0");

        jLabel1.setText("Product Name:");

        jLabel2.setText("Price:");

        jLabel3.setText("Quantity:");

        btnUpdate.setText("Update Price");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(stockProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stockPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(stockQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(stockSearch)
                    .addComponent(jScrollPane1))
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(loadDataStock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removeItemStock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addItemStock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchItemStock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stockSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchItemStock))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stockProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stockPrice))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addItemStock)
                            .addComponent(stockQuantity))
                        .addGap(18, 18, 18)
                        .addComponent(removeItemStock)
                        .addGap(18, 18, 18)
                        .addComponent(loadDataStock)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Stock", jPanel2);

        reportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Item", "Quantiy", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(reportTable);
        if (reportTable.getColumnModel().getColumnCount() > 0) {
            reportTable.getColumnModel().getColumn(0).setResizable(false);
            reportTable.getColumnModel().getColumn(1).setResizable(false);
            reportTable.getColumnModel().getColumn(2).setResizable(false);
            reportTable.getColumnModel().getColumn(3).setResizable(false);
        }

        genReport.setText("Generate Report");
        genReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genReportActionPerformed(evt);
            }
        });

        btnDownload.setText("Download");
        btnDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(genReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDownload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(genReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDownload)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Report", jPanel3);

        performLogout.setText("Logout");
        performLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(performLogout)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(performLogout)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void performLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performLogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_performLogoutActionPerformed

    private void loadDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadDataActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) sellTable.getModel();
        loadTable(model);
    }//GEN-LAST:event_loadDataActionPerformed

    private void addDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDataActionPerformed
        // TODO add your handling code here:
        // Get the selected row from sellTable
        DefaultTableModel sellModel = (DefaultTableModel) sellTable.getModel();
        DefaultTableModel basketModel = (DefaultTableModel) basketTable.getModel();

        int selectedRow = sellTable.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Please select a product!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Fetch selected product details safely
        int id = (int) sellModel.getValueAt(selectedRow, 0);
        String name = (String) sellModel.getValueAt(selectedRow, 1);

        int availableQuantity;
        availableQuantity = (int) sellModel.getValueAt(selectedRow, 2);

        // Handling price safely
        double price = (double) sellModel.getValueAt(selectedRow, 3);

        // Ask user for quantity input
        String quantityStr = JOptionPane.showInputDialog(null,
                "Enter quantity for " + name + " (Available: " + availableQuantity + ")",
                "Select Quantity",
                JOptionPane.QUESTION_MESSAGE);

        if (quantityStr == null) {
            return; // User pressed cancel
        }
        try {
            int quantity = Integer.parseInt(quantityStr);

            if (quantity <= 0) {
                JOptionPane.showMessageDialog(null, "Quantity must be greater than 0!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (quantity > availableQuantity) {
                JOptionPane.showMessageDialog(null, "Insufficient stock!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Check if the item already exists in basketTable
            boolean itemExists = false;
            for (int i = 0; i < basketModel.getRowCount(); i++) {
                if ((int) basketModel.getValueAt(i, 0) == id) {
                    // Item found, update quantity and total price
                    int existingQuantity = (int) basketModel.getValueAt(i, 3);
                    int newQuantity = existingQuantity + quantity;
                    double newTotalPrice = newQuantity * price;

                    basketModel.setValueAt(newQuantity, i, 3); // Update quantity
                    basketModel.setValueAt(newTotalPrice, i, 4); // Update total price
                    itemExists = true;
                    break;
                }
            }

            if (!itemExists) {
                // Add item to basketTable if it doesn't exist
                double totalPrice = price * quantity;
                basketModel.addRow(new Object[]{id, name, price, quantity, totalPrice});
            }

            // Reduce quantity in sellTable
            sellModel.setValueAt(availableQuantity - quantity, selectedRow, 2);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid quantity entered!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addDataActionPerformed

    private void editQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editQuantityActionPerformed
        // TODO add your handling code here:
        DefaultTableModel basketModel = (DefaultTableModel) basketTable.getModel();
        DefaultTableModel sellModel = (DefaultTableModel) sellTable.getModel();

        int selectedRow = basketTable.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Please select a product from the basket!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Fetch selected product details
        int id = (int) basketModel.getValueAt(selectedRow, 0);
        String name = (String) basketModel.getValueAt(selectedRow, 1);
        double price = (double) basketModel.getValueAt(selectedRow, 2);
        int currentBasketQuantity = (int) basketModel.getValueAt(selectedRow, 3);

        // Find the corresponding row in sellTable
        int sellRow = -1;
        for (int i = 0; i < sellModel.getRowCount(); i++) {
            if ((int) sellModel.getValueAt(i, 0) == id) {
                sellRow = i;
                break;
            }
        }

        if (sellRow == -1) {
            JOptionPane.showMessageDialog(null, "Product not found in sell table!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int availableSellQuantity = (int) sellModel.getValueAt(sellRow, 2);
        int totalStock = availableSellQuantity + currentBasketQuantity;

        // Show input dialog for updated quantity
        String quantityStr = JOptionPane.showInputDialog(null,
                "Enter new quantity for " + name + " (Available: " + totalStock + ")",
                "Edit Quantity",
                JOptionPane.QUESTION_MESSAGE);

        if (quantityStr == null) {
            return; // User pressed cancel
        }
        try {
            int newQuantity = Integer.parseInt(quantityStr);

            if (newQuantity <= 0) {
                JOptionPane.showMessageDialog(null, "Quantity must be greater than 0!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (newQuantity > totalStock) {
                JOptionPane.showMessageDialog(null, "Insufficient stock!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Update basketTable with new quantity and total price
            double newTotalPrice = newQuantity * price;
            basketModel.setValueAt(newQuantity, selectedRow, 3);
            basketModel.setValueAt(newTotalPrice, selectedRow, 4);

            // Update sellTable available quantity
            sellModel.setValueAt(totalStock - newQuantity, sellRow, 2);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid quantity entered!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_editQuantityActionPerformed

    private void confirmSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmSaleActionPerformed
        // TODO add your handling code here:
        DefaultTableModel basketModel = (DefaultTableModel) basketTable.getModel();
        DefaultTableModel sellModel = (DefaultTableModel) sellTable.getModel();

        if (basketModel.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Basket is empty!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Connection conn = null;
        PreparedStatement saleStmt = null;
        PreparedStatement updateStmt = null;

        try {
            dbConnect db = new dbConnect();
            db.connect();
            conn = db.getConnection();
            conn.setAutoCommit(false); // Start transaction

            // Insert into sales table
            String insertSaleSQL = "INSERT INTO sales(saleDate, item,quantity,total) VALUES(NOW(),?,?,?)";

            saleStmt = conn.prepareStatement(insertSaleSQL);

            for (int i = 0; i < basketModel.getRowCount(); i++) {
                saleStmt.setString(1, (String) (basketModel.getValueAt(i, 1)));
                saleStmt.setInt(2, (int) basketModel.getValueAt(i, 3));
                saleStmt.setDouble(3, (double) basketModel.getValueAt(i, 4));
                saleStmt.addBatch();
            }

            saleStmt.executeBatch();

            // Update product quantities based on sellTable
            String updateProductSQL = "UPDATE products SET quantity = ? WHERE id = ?";
            updateStmt = conn.prepareStatement(updateProductSQL);

            for (int i = 0; i < sellModel.getRowCount(); i++) {
                int productId = (int) sellModel.getValueAt(i, 0);
                int newQuantity = (int) sellModel.getValueAt(i, 2); // Updated available quantity

                updateStmt.setInt(1, newQuantity);
                updateStmt.setInt(2, productId);
                updateStmt.addBatch(); // Batch update for efficiency
            }

            updateStmt.executeBatch();
            conn.commit(); // Commit transaction

            // Clear basket table
            basketModel.setRowCount(0);

            JOptionPane.showMessageDialog(null, "Sale confirmed!", "Success", JOptionPane.INFORMATION_MESSAGE);

        } catch (SQLException e) {
            if (conn != null) {
                try {
                    conn.rollback();
                } catch (SQLException ex) {
                }
            }
            JOptionPane.showMessageDialog(null, "Error processing sale!", "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (saleStmt != null) {
                    saleStmt.close();
                }
                if (updateStmt != null) {
                    updateStmt.close();
                }
                if (conn != null) {
                    conn.setAutoCommit(true);
                }
            } catch (SQLException e) {
            }
        }
    }//GEN-LAST:event_confirmSaleActionPerformed

    private void genReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genReportActionPerformed
        DefaultTableModel reportModel = (DefaultTableModel) reportTable.getModel();
        reportModel.setRowCount(0); // Clear previous data

        Connection conn = null;
        PreparedStatement stmt = null;
        ResultSet rs = null;

        try {
            dbConnect db = new dbConnect();
            db.connect();
            conn = db.getConnection();

            // Retrieve sales data
            String query = "SELECT saleDate, item, quantity, total FROM sales";
            stmt = conn.prepareStatement(query);
            rs = stmt.executeQuery();

            while (rs.next()) {
                String date = rs.getString("saleDate");
                String itemName = rs.getString("item");
                int quantity = rs.getInt("quantity");
                double total = rs.getDouble("total");

                // Add row to reportTable
                reportModel.addRow(new Object[]{date, itemName, quantity, total});
            }

            JOptionPane.showMessageDialog(null, "Report generated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error generating report!", "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (stmt != null) {
                    stmt.close();
                }
            } catch (SQLException e) {
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_genReportActionPerformed

    private void btnDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Save Report");
        fileChooser.setSelectedFile(new File("Sales_Report.csv"));

        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            saveReportAsCSV(fileToSave.getAbsolutePath());
        }
    }//GEN-LAST:event_btnDownloadActionPerformed

    private void searchItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchItemActionPerformed
        // TODO add your handling code here:    // Get trimmed search text
        String searchText = sellSearch.getText().trim();

        // Check if the search text is empty
        if (searchText.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter a search term!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Connect to DB
        dbConnect db = new dbConnect();
        db.connect();
        Connection conn = db.getConnection();

        // Define query using wildcard search
        String query = "SELECT * FROM products WHERE name LIKE '%" + searchText + "%'";

        try (Statement stmt = conn.createStatement(); ResultSet rs = stmt.executeQuery(query)) {

            // Create table model
            DefaultTableModel model = (DefaultTableModel) sellTable.getModel();
            model.setRowCount(0); // Clear previous results

            // Populate table with results
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("name"),
                    rs.getInt("quantity"),
                    rs.getDouble("price")
                });
            }

        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_searchItemActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int selectedRow = stockTable.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a row to update.", "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Assuming column 0 = ID, column 1 = price
        int id = (int) stockTable.getValueAt(selectedRow, 0);
        double currentPrice = (double) stockTable.getValueAt(selectedRow, 3);

        String newPriceStr = JOptionPane.showInputDialog(this, "Set new price:", currentPrice);
        if (newPriceStr == null) {
            return; // User cancelled
        }
        try {
            double newPrice = Double.parseDouble(newPriceStr);

            dbConnect db = new dbConnect();
            db.connect();
            Connection con = db.getConnection();

            String sql = "UPDATE products SET price = ? WHERE id = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setDouble(1, newPrice);
            pst.setInt(2, id);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Price updated successfully.");
            db.closeConnection();
            loadTable((DefaultTableModel) stockTable.getModel());

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid price entered.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void loadDataStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadDataStockActionPerformed

        DefaultTableModel model = (DefaultTableModel) stockTable.getModel();
        loadTable(model);
    }//GEN-LAST:event_loadDataStockActionPerformed

    private void removeItemStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeItemStockActionPerformed
        // TODO add your handling code here:
        int selectedRow = stockTable.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Please select an item to remove!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Get the item ID from the selected row (assuming ID is in column 0)
        int itemId = (int) stockTable.getValueAt(selectedRow, 0);

        // Confirm deletion
        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this item?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        // Connect to the database
        dbConnect db = new dbConnect();
        db.connect();
        Connection conn = db.getConnection();

        // Delete the item from the database
        String query = "DELETE FROM products WHERE id = " + itemId;

        try (Statement stmt = conn.createStatement()) {
            int rowsAffected = stmt.executeUpdate(query);

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Item removed successfully!");

                // Remove the row from the table
                DefaultTableModel model = (DefaultTableModel) stockTable.getModel();
                model.removeRow(selectedRow);
            } else {
                JOptionPane.showMessageDialog(null, "Item not found in database!", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_removeItemStockActionPerformed

    private void addItemStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemStockActionPerformed
        // TODO add your handling code here:
        String name = stockProductName.getText().trim();
        String priceText = stockPrice.getText().trim();
        String quantityText = stockQuantity.getText().trim();

        if (name.isEmpty() || priceText.isEmpty() || quantityText.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Fill Up All Boxes", "Error", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        String sql = "INSERT INTO products(name, price, quantity) VALUES(?, ?, ?)";

        try {
            double price = Double.parseDouble(priceText);
            int quantity = Integer.parseInt(quantityText);

            if (price <= 0 || quantity <= 0) {
                JOptionPane.showMessageDialog(null, "Price and Quantity must be greater than 0", "Error", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            dbConnect db = new dbConnect();
            db.connect();
            Connection conn = db.getConnection();

            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, name);
            pstmt.setDouble(2, price);
            pstmt.setInt(3, quantity);

            int rowsInserted = pstmt.executeUpdate();

            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(null, "Product Added Successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                loadTable((DefaultTableModel) stockTable.getModel());
            } else {
                JOptionPane.showMessageDialog(null, "Failed to add product.", "Error", JOptionPane.ERROR_MESSAGE);
            }

            pstmt.close();
            conn.close();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid number format for Price or Quantity", "Error", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Database Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addItemStockActionPerformed

    private void searchItemStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchItemStockActionPerformed
        // TODO add your handling code here:
        String searchText = stockSearch.getText().trim();

        // Check if the search text is empty
        if (searchText.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter a search term!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Connect to DB
        dbConnect db = new dbConnect();
        db.connect();
        Connection conn = db.getConnection();

        // Define query using wildcard search
        String query = "SELECT * FROM products WHERE name LIKE '%" + searchText + "%'";

        try (Statement stmt = conn.createStatement(); ResultSet rs = stmt.executeQuery(query)) {

            // Create table model
            DefaultTableModel model = (DefaultTableModel) stockTable.getModel();
            model.setRowCount(0); // Clear previous results

            // Populate table with results
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("name"),
                    rs.getInt("quantity"),
                    rs.getDouble("price")
                });
            }

        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_searchItemStockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainWindow().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addData;
    private javax.swing.JButton addItemStock;
    private javax.swing.JTable basketTable;
    private javax.swing.JButton btnDownload;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton confirmSale;
    private javax.swing.JButton editQuantity;
    private javax.swing.JButton genReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton loadData;
    private javax.swing.JButton loadDataStock;
    private javax.swing.JButton performLogout;
    private javax.swing.JButton removeItemStock;
    private javax.swing.JTable reportTable;
    private javax.swing.JButton searchItem;
    private javax.swing.JButton searchItemStock;
    private javax.swing.JTextField sellSearch;
    private javax.swing.JTable sellTable;
    private javax.swing.JTextField stockPrice;
    private javax.swing.JTextField stockProductName;
    private javax.swing.JTextField stockQuantity;
    private javax.swing.JTextField stockSearch;
    private javax.swing.JTable stockTable;
    // End of variables declaration//GEN-END:variables
}
